In [22]:
import tensorflow as tf
import numpy as np

In [4]:
# Defining Constant

five = tf.constant(5)

two = tf.constant(2)

four = tf.constant(4)

# Multiply op
mul = tf.multiply(five, two)

# Subtract op
sub = tf.subtract(four, two)

# Add op
add = tf.add(five, four)

# Create Session
sess = tf.Session()

out_mul = sess.run(mul)
out_sub = sess.run(sub)
out_add = sess.run(add)

# Close session
sess.close()

print('Mul: {}'.format(out_mul))
print('Sub: {}'.format(out_sub))
print('Add: {}'.format(out_add))


Mul: 10
Sub: 2
Add: 9


## Understanding Graphs

Learn different ways of creating a tensorflow graph

In [6]:
print(tf.get_default_graph())

g = tf.Graph()
print(g)

In [8]:
print(five.graph is g)
print(five.graph is tf.get_default_graph())

False
True


In [11]:
g1 = tf.get_default_graph()
g2 = tf.Graph()

print(g1 is tf.get_default_graph())

with g2.as_default():
    # Here scope is changed
    print(g1 is tf.get_default_graph())

print(g1 is tf.get_default_graph())

True
False
True


## Create session - No need to explicity close the session

In [12]:
with tf.Session() as sess:
    out = sess.run(five)

print("out: {}".format(out))

out: 5


## Nodes, Tensor Objects, Data types

- Operations are considered as Nodes
- Tensors are basically Arrays

In [21]:
four = tf.constant(4)
print(four)

print(four.dtype)

arr = tf.constant(
    [10, 20, 30, 40, 50],
    name='arr',
    dtype=tf.float32
)

print('\r\nOutput: {}'.format(arr))
print('\r\nType: {}'.format(arr.dtype))

Tensor("Const_17:0", shape=(), dtype=int32)
<dtype: 'int32'>

Output: Tensor("arr_4:0", shape=(5,), dtype=float32)

Type: <dtype: 'float32'>


In [26]:
two_dim = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
print('Shape of 2d list: {}'.format(two_dim.get_shape()))

three_dim = tf.constant(np.array([
                        [[1, 2, 3], [4, 5, 6]],

                        [[7, 8, 9], [0, 1, 2]]
                        ]))

print('Shape of 3d list: {}'.format(three_dim.get_shape()))

Shape of 2d list: (2, 3)
Shape of 3d list: (2, 2, 3)


## Understanding Names, Names scopes, Variables and Placeholders

In [33]:
with tf.Graph().as_default():
    constant1 = tf.constant(1, dtype=tf.float64, name='const1')
    constant2 = tf.constant(2, dtype=tf.int32, name='const2')
    
    constant3 = tf.constant(3, dtype=tf.float64, name='const1')
    constant4 = tf.constant(4, dtype=tf.int32, name='const2')

print(constant1.name)
print(constant2.name)
print(constant3.name)
print(constant4.name)

const1:0
const2:0
const1_1:0
const2_1:0


In [35]:
# Name Scopes
# Using prefix_name

with tf.Graph().as_default():
    constant1 = tf.constant(1, dtype=tf.float64, name='const1')
    with tf.name_scope("Prefix"):
        constant2 = tf.constant(1, dtype=tf.float64, name='const1')
        constant3 = tf.constant(1, dtype=tf.float64, name='const1')

print(constant1.name)
print(constant2.name)
print(constant3.name)

const1:0
Prefix/const1:0
Prefix/const1_1:0


In [38]:
# Variables

var1 = tf.Variable([[1, 1, 1], [4, 5, 6]], name='var')
print("pre run: \n{}".format(var1))

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    out = sess.run(var1)

print("\npost run: \n{}".format(out))

pre run: 
<tf.Variable 'var_2:0' shape=(2, 3) dtype=int32_ref>

post run: 
[[1 1 1]
 [4 5 6]]


In [47]:
# Placeholders

# Generate data for the placeholders
x_data = np.random.randn(3, 5)
y_data = np.random.randn(5, 2)

with tf.Graph().as_default():
    
    # Create placeholder, define data type and shape
    x = tf.placeholder(tf.float32, shape=(3, 5))
    y = tf.placeholder(tf.float32, shape=(5, 2))
    
    # Run matrix multiplication op on placeholders
    xy = tf.matmul(x, y)
    
    with tf.Session() as sess:
        out = sess.run(xy, feed_dict={x: x_data, y: y_data})

print("Matrix Multiplication result is:\r\n{}".format(out))
    

Matrix Multiplication result is:
[[-2.6689072 -1.1418684]
 [ 3.6265526 -2.0389369]
 [-2.2144015 -2.1633053]]
